server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host localhost:8080;
        proxy_set_header X-Forwarded-Host localhost:8080;
        proxy_set_header X-Forwarded-Port 8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
    }

    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host:$server_port;
    }

    location /media/ {
        alias /app/media/;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}