# Generated by Django 6.0.3 on 2026-04-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
