LOCAL_NAMES = (
    'La Taberna del Puerto',
    'El Rincón de la Tortilla',
    'Casa Pepe',
    'Mesón el Segoviano',
    'Brasería Los Olivos',
    'Marisquería Bahía',
    'Restaurante El Quijote',
    'La Parrilla de Alberto',
    'Taberna Real',
    'El Asador de Aranda',
    'La Bodeguita de Enmedio',
    'El Fogón de Leña',
    'Taberna los Volcanes',
    'Restaurante Miramar',
    'El Txoko de Vitoria',
    'Sabor a Mar',
    'Cervecería La Caña',
    'Mesón de las Letras',
    'La Venta del Sol',
    'Restaurante San Isidro',
    'El Rincón Gallego',
    'Tapas y Tragos',
    'La Posada del Duende',
    'El Cenador de Salvador',
    'Rincón Gourmet',
    'La Trattoria de la Abuela',
    'El Mirador del Valle',
    'Bodegas del Campo',
    'Terraza El Faro',
    'El Molino de Piedra',
    'La Cueva del Vino',
    'Restaurante Central',
    'Taberna de los Austrias',
    'Entre Fogones',
    'El Patio de los Naranjos',
    'La Despensa de Paco',
    'Asador Don Juan',
    'El Callejón del Sabor',
    'Mesón el Arriero',
    'La Lonja de San Pedro',
    'Brasas y Copas',
    "Restaurante L'Antiga",
    'La Dehesa de Extremadura',
    'El Picoteo de la Plaza',
    'Taberna de Baco',
    'El Refugio de la Montaña',
    'Casa Manolo',
    'La Tabernita de Gràcia',
    'Restaurante El Jardín',
    'El Bodegón del Siglo',
    'La Estación del Gusto',
    'Mesón de la Abuela',
    'Gastrobar La Esquina',
    'La Choza del Sabor',
    'Restaurante Victoria',
    'El Faro de la Costa',
    'La Tasca del Sur',
    'Brasería La Pampa',
    'El Mesón de la Plaza',
    'La Gastroteca',
    'Taberna El Olivo',
    'El Rincón de las Tapas',
    'Asador El Roble',
    'La Despensa Real',
    'Restaurante Las Palmeras',
    'El Patio Andaluz',
    'Taberna Los Madroños',
    'El Rincón Extremeño',
    'Marisquería El Ancla',
    'La Brasería de la Esquina',
    'Restaurante Horizonte',
    'El Mesón del Vino',
    'La Taberna de las Flores',
    'El Rincón del Chef',
    'Asador La Encina',
    'La Cocina de Mamá',
    'El Pósito de la Mar',
    'Taberna La Muralla',
    'Restaurante El Torreón',
    'La Posada de San Juan',
    'El Bodegón de Oro',
)
