# Generated by Django 6.0.2 on 2026-02-11 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('icon', models.ImageField(blank=True, default='allergens/noallergen.png', null=True, upload_to='allergens/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='establishments.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_type', models.CharField(choices=[('meat', 'Meat'), ('fish', 'Fish'), ('vegetables', 'Vegetables'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('sauces', 'Sauces'), ('drinks', 'Drinks'), ('other', 'Other')], default='other')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('allergens', models.ManyToManyField(blank=True, related_name='ingredients', to='products.allergen')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='establishments.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True)),
                ('product_image', models.ImageField(default='products/noproduct.png', upload_to='products')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='establishments.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unity', models.CharField(choices=[('ea', 'Unity'), ('gr', 'Grams'), ('kg', 'Kilograms'), ('l', 'Liters'), ('ml', 'Mililiters')], max_length=2)),
                ('removable', models.BooleanField(default=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='products.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='products.product')),
            ],
        ),
    ]
