# Generated by Django 6.0.2 on 2026-02-10 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='establishments.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('drinks', 'Drinks'), ('desserts', 'Desserts'), ('food', 'Food')])),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True)),
                ('product_image', models.ImageField(default='products/noproduct.png', upload_to='products')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available', models.BooleanField(default=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='establishments.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unity', models.CharField(choices=[('ud', 'Unity'), ('gr', 'Grams'), ('kg', 'Kilograms'), ('l', 'Liters'), ('ml', 'Mililiters'), ('cl', 'Centiliters')], max_length=2)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='products.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='products.product')),
            ],
        ),
    ]
