# Generated by Django 6.0.2 on 2026-02-11 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('legal_name', models.CharField()),
                ('cif', models.CharField(max_length=9, unique=True)),
                ('description', models.TextField(blank=True)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=16)),
                ('opened', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('waiter', 'Waiter'), ('manager', 'Manager'), ('kitchen', 'Kitchen')])),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manages', to='establishments.establishment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_guests', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='establishments.establishment')),
            ],
        ),
    ]
