# Generated by Django 6.0.2 on 2026-02-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('establishment', 'number')},
        ),
    ]
