# Generated by Django 6.0.3 on 2026-03-31 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('waiter', 'Waiter'), ('manager', 'Manager'), ('kitchen', 'Kitchen')], default='waiter', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='establishments.establishment')),
            ],
        ),
    ]
