# Generated by Django 6.0.3 on 2026-04-11 22:00

import django.core.validators
import establishments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='cif',
            field=models.CharField(max_length=9, unique=True, validators=[establishments.models.validate_cif]),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='legal_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='phone',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Invalid phone number.')]),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='zip_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{4,10}$', 'Invalid zip code.')]),
        ),
    ]
