# Generated by Django 6.0.3 on 2026-05-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='manager_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
